### Import & Create Data

In [28]:
import numpy as np
fitness_data = np.array([
    [5000, 200, 6],
    [7000, 250, 7],
    [6500, 230, 6],
    [8000, 300, 8],
    [9000, 320, 7],
    [7500, 270, 6],
    [12000, 400, 5]])
    


### Explore the Array

In [29]:
print("Number of Dimensions:", fitness_data.ndim)
print("Shape:", fitness_data.shape)
print("Total Number of Elements:", fitness_data.size)

Number of Dimensions: 2
Shape: (7, 3)
Total Number of Elements: 21


### Slice the Data

In [30]:
steps = fitness_data[:, 0]
calories = fitness_data[:, 1]
sleep = fitness_data[:, 2]

print("Steps:")
print(steps)

print("\nCalories:")
print(calories)

print("\nSleep Hours:")
print(sleep)

print("\nFirst 3 Days:")
print(fitness_data[:3])

print("\nSteps and Calories:")
print(fitness_data[:, :2])

Steps:
[ 5000  7000  6500  8000  9000  7500 12000]

Calories:
[200 250 230 300 320 270 400]

Sleep Hours:
[6 7 6 8 7 6 5]

First 3 Days:
[[5000  200    6]
 [7000  250    7]
 [6500  230    6]]

Steps and Calories:
[[ 5000   200]
 [ 7000   250]
 [ 6500   230]
 [ 8000   300]
 [ 9000   320]
 [ 7500   270]
 [12000   400]]


### Reshape the Data

In [31]:
steps_column = steps.reshape(7, 1)

print("Steps Reshaped to (7,1):")
print(steps_column)

reshaped_data = fitness_data.reshape(3, 7)

print("\nDataset Reshaped to (3,7):")
print(reshaped_data)

Steps Reshaped to (7,1):
[[ 5000]
 [ 7000]
 [ 6500]
 [ 8000]
 [ 9000]
 [ 7500]
 [12000]]

Dataset Reshaped to (3,7):
[[ 5000   200     6  7000   250     7  6500]
 [  230     6  8000   300     8  9000   320]
 [    7  7500   270     6 12000   400     5]]


### Filter the Data

In [32]:
print("Steps > 8000")
print(fitness_data[fitness_data[:, 0] > 8000])

print("\nSleep < 6")
print(fitness_data[fitness_data[:, 2] < 6])

print("\nCalories > 300")
print(fitness_data[fitness_data[:, 1] > 300])

Steps > 8000
[[ 9000   320     7]
 [12000   400     5]]

Sleep < 6
[[12000   400     5]]

Calories > 300
[[ 9000   320     7]
 [12000   400     5]]


### Statistical Functions

In [ ]:
print("Average Steps:", np.mean(steps))
print("Maximum Steps:", np.max(steps))
print("Minimum Sleep Hours:", np.min(sleep))

print("Standard Deviation of Calories:", np.std(calories))

print("Range of Steps:", np.ptp(steps))

Average Steps: 7857.142857142857
Maximum Steps: 12000
Minimum Sleep Hours: 5
Standard Deviation of Calories: 61.278887398649196
Range of Steps: 7000


: 

### Insights

## Insights

### Patterns
- Calories burned increase as the number of steps increases.
- Most days have between 6 and 7 hours of sleep.

### Unusual Day
- The day with 12,000 steps and 400 calories burned is the most active.
- It also has the lowest sleep duration (5 hours).

### What I Learned
- More physical activity usually burns more calories.
- High activity does not always mean enough sleep.